#!/usr/bin/env python
# coding: utf-8

# In[19]:


import pandas as pd
file_path = 'D:\\Fifa.csv'


df = pd.read_csv(file_path)



print("Dataset Loaded Successfully!")
print(df.head())



print("First 10 rows of the dataset:")
print(df.head(10))

print("\nLast 10 rows of the dataset:")
print(df.tail(10))




print("Basic Statistics of the dataset:")
print(df.describe())

print(f"Mean:")
print(df.mean())

print(f"Median:")
print(df.median())

print(f"mode:")
print(df.mode())  



df_filled_values = df.fillna(df.mean(numeric_only=True))


print("\nMissing values after handling:")
print(df_filled_values.isnull().sum())


print("\nDataset after handling missing values:")
print(df_filled_values.head())


# In[20]:


import pandas as pd

file_path = 'D:\\1000 Movies Data.csv'  


df = pd.read_csv(file_path)
print("Dataset Loaded Successfully!")
print(df.head())


print(f"first 10 rows of the data set")
print(df.head(10))


print(f"last 10 rows of the data set")
print(df.tail(10))


print(f"basic structure of dataset")
print(df.describe())


print(f"mean")
print(df.mean())



print(f"median")
print(df.median())



print(f"mode")
print(df.mode())



df_filled_values = df.fillna(df.mean(numeric_only=True))


print("\nMissing values after handling:")
print(df_filled_values.isnull().sum())


print("\nDataset after handling missing values:")
print(df_filled_values.head())


# In[24]:


#TASK2 PART 1 
import pandas as pd

file_path = 'D:\\1000 Movies Data.csv'  

df = pd.read_csv(file_path)

print("Column names in the dataset:")
print(df.columns)

sorted_movies = df.sort_values(by=['Rating', 'Votes'], ascending=False)
top_10_movies = sorted_movies.head(10)


print("\nTop 10 movies based on Rating and Votes:")
print(top_10_movies[['Title', 'Rating', 'Votes']])


# In[45]:


#task2 part 2 
import matplotlib.pyplot as plt

import pandas as pd

file_path = 'D:\\1000 Movies Data.csv'  

df = pd.read_csv(file_path)
missing_rating = df['Rating'].isnull().sum()
missing_revenue = df['Revenue (Millions)'].isnull().sum()

print(f"Missing values in 'Rating': {missing_rating}")
print(f"Missing values in 'Revenue (Millions)': {missing_revenue}")

df_cleaned = df[['Rating', 'Revenue (Millions)']].dropna()

print(f"Dataset after removing missing values:")
print(df_cleaned.head())



correlation=df['Rating'].corr(df['Revenue (Millions)'])
print(correlation)

correlation=df['Rating'].corr(df['Runtime (Minutes)'])
print(correlation)


# In[36]:


import pandas as pd

file_path = 'D:\\1000 Movies Data.csv'  
print(df['Director'])
director_name=input(f"enter the name of the director")



director_movies=df[df['Director']==director_name]

average_runtime=director_movies['Runtime (Minutes)'].mean()

print(f"average of{director_name} in minutes is:{average_runtime:.2f} ")


# In[40]:


import pandas as pd

file_path = 'D:\\1000 Movies Data.csv'  
average_ratings=df.groupby('Genre')['Rating'].mean()

top_genre = average_ratings.idxmax()
top_genre_rating = average_ratings.max()

print(f"The highest average genre {top_genre} with the average is {top_genre_rating:.2f}")


# In[42]:


import pandas as pd

file_path = 'D:\\1000 Movies Data.csv'  
print(df['Year'])
year=int(input(f"enter the year"))  

total_revenue = df[df['Year'] == year]['Revenue (Millions)'].sum()

print(f"The total revenue generated by movies released in {year} is ${total_revenue} million.")


# In[46]:


import pandas as pd

file_path = 'D:\\1000 Movies Data.csv' 

director_movies = df['Director'].value_counts()

top_director = director_movies.idxmax()
count = director_movies.max()

print(f"The director won top is {top_director} with {count} movies.")



# In[48]:


import pandas as pd

file_path = 'D:\\1000 Movies Data.csv' 
correlation_runtime_rating = df['Runtime (Minutes)'].corr(df['Rating'])

print(correlation_runtime_rating)


# In[49]:


import pandas as pd
import matplotlib.pyplot as plt


file_path = 'D:\\1000 Movies Data.csv' 
df = pd.read_csv(file_path)


plt.figure(figsize=(10, 6))
plt.hist(df['Runtime (Minutes)'].dropna(), bins=30, color='skyblue', edgecolor='black')
plt.title(' Durationsof movies ')
plt.xlabel('Runtime (Minutes)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()


# In[51]:


import pandas as pd
import matplotlib.pyplot as plt

file_path = 'D:\\1000 Movies Data.csv' 
df = pd.read_csv(file_path)
plt.figure(figsize=(10, 6))
plt.hist(df['Rating'].dropna(), bins=20, color='pink', edgecolor='black')
plt.title('Distribution of Movie Ratings')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()


# In[52]:


import pandas as pd
import matplotlib.pyplot as plt

file_path = 'D:\\1000 Movies Data.csv' 
average_rating_by_genre = df.groupby('Genre')['Rating'].mean()

top_10_genres = average_rating_by_genre.sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 6))
top_10_genres.plot(kind='bar', color='yellow', edgecolor='black')
plt.title('Top 10 Genres by Average Rating')
plt.xlabel('Genre')
plt.ylabel('Average Rating')
plt.xticks(rotation=45, ha='right')
plt.show()


# In[53]:


import pandas as pd
import matplotlib.pyplot as plt

file_path = 'D:\\1000 Movies Data.csv' 
data = {'Footballer': ['Lionel Messi', 'Cristiano Ronaldo', 'Neymar', 'Kylian Mbappé', 'Mohamed Salah'],
        'Salary (Millions)': [130, 120, 95, 100, 60]}

df_footballers = pd.DataFrame(data)


plt.figure(figsize=(10, 6))
plt.bar(df_footballers['Footballer'], df_footballers['Salary (Millions)'], color='orange')
plt.title('World\'s Highest Paid Footballers')
plt.xlabel('Footballer')
plt.ylabel('Salary (Millions)')
plt.xticks(rotation=45, ha='right')
plt.show()


# In[ ]:




